### ISSUE TITLE
AutoDrive v1.0.5 Freeze Game

### ISSUE THREAD

**Issue by lgorek** [Stephan-S/AutoDrive#5]
I have install AD 1.0.5 and have problem with freeze game

>  C:/Users/lgor/Documents/My Games/FarmingSimulator2017/mods/AutoDrive/AutoDrive.lua:3926: attempt to index a nil value
> Error: Running LUA method 'update'.

I have over 10k lines of this error in log file. Only solution when its happend is ctrl+alt+del. But the funniest part is that we can export AD config when its on :)

Some My Sugestion
1. Button [A]=auto, [S]=short, [L]=long create lines. For example we go far straight [L] and we need add crossroad then we change to [S] and is simple to make better conections. 
2. Button [UNDO] when we for misstake delete dot and destroy our net. 
3. When we have selected [White Line =show neighbor point] and turn on record, mod automatic connect new record point with this white line and create continuous line, and the same when we and. It will easy way to creats routes.
4. Button [OFF], [0%] and [100%], when we collect grass or others when it reach 100% AD is still continous his way. If we have option set that after he reach 100% he will PAUSE. It helpful when someone create long route for baler and AD dont stop to unload round baler, when we had installer auto unload mod. 

Best Regars
JK

**Comment by Stephan-S** [comment]
1+2: My problem is that I of course could add hundreds of buttons with a hundred different nice little features, but in the end its only getting more and more complex and nobody will be using it because nobody is willing to spend so mucht time getting to know the controls :(

For 3, I will try to implement it, but my problem is that the logic is reversed if you connect the white line towards the blue line at the start :D. Very good idea anyhow and I will probably do it that way

4: For field work, I suggest using Courseplay since this is not how AutoDrive should be used

**Comment by lgorek** [comment]
Ad1. Maybe add simplest solution for example, when we drive fast the record AD make less but longer routes, but when we will drive slow it make more shorter ones. No buttons and create longer and shorter lines. We can set course for 10km/h and make 100points, or set course for 30km/h and make 50points at the same distanse. In brief go faster less points, go slower more points.  
Ad4. Courseplay its not for me to more power full and now fun with play :),but iIt would be great as AutoDrive will cooperate with driveControl. There is that option that stop0% or stop100%. But when i set it now, nothing happend and AD goes further. 

Did u check what is an error line 3926 which freeze FS17 ?

**Comment by Stephan-S** [comment]
Yes, I did, should be fixed in 1.0.6
But for the other parts, im sorry but i probably wont be able to do anything until early January since im away over Christmas :-)
